### ISSUE TITLE
Script not passing the captchas

### ISSUE THREAD

**Issue by iplaywithdrums** [ariffjeff/ReEmployCT-Data-Entry#41]
**Describe the bug**
After running the script, there are two places that have captchas that stopped the script:
1. When logging in
2. Starting to enter the data

Is it intended behavior to have to click the captchas myself manually?

**Comment by ariffjeff** [comment]
That's normal behavior. It can't pass the captchas automatically. You can watch the video tutorial in the readme to see what you can expect.

**Comment by iplaywithdrums** [comment]
Ah looks like the second captcha is expected as well. Thanks!

![image](https://github.com/user-attachments/assets/f0a4af61-068c-48f2-a28b-5e6d7a5d3d84)
